steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/sql-sensi/sql-sensi:latest', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/sql-sensi/sql-sensi:latest']
images:
  - 'gcr.io/sql-sensi/sql-sensi:latest'
